Repository eigerco/polka-storage, pull requests merged in 2024-12, with the labels that each got.

#619 docs: add a point about ubuntu 24.04
  docs/src/getting-started/building/source.md
  docs/src/getting-started/index.md
  docs/src/getting-started/local-testnet/index.md
  docs/src/introduction.md
Labels: documentation, ready for review

#617 feat(polka-storage-provider): submit PoSt on the pipeline
  docs/src/getting-started/storage-provider.md
  examples/rpc_publish.sh
  lib/polka-storage-proofs/src/lib.rs
  lib/polka-storage-proofs/src/post/mod.rs
  maat/tests/real_world.rs
  pallets/storage-provider/src/deadline.rs
  pallets/storage-provider/src/expiration_queue.rs
  pallets/storage-provider/src/fault.rs
  pallets/storage-provider/src/lib.rs
  pallets/storage-provider/src/partition.rs
  pallets/storage-provider/src/proofs.rs
  pallets/storage-provider/src/sector.rs
  pallets/storage-provider/src/sector_map.rs
  pallets/storage-provider/src/storage_provider.rs
  pallets/storage-provider/src/tests/expiration_queue.rs
  pallets/storage-provider/src/tests/mod.rs
  pallets/storage-provider/src/tests/post_hook.rs
  pallets/storage-provider/src/tests/submit_windowed_post.rs
  pallets/storage-provider/src/tests/terminate_sectors.rs
  primitives/Cargo.toml
  primitives/src/lib.rs
  primitives/src/pallets.rs
  runtime/src/lib.rs
  storage-provider/common/src/rpc/mod.rs
  storage-provider/server/Cargo.toml
  storage-provider/server/src/main.rs
  storage-provider/server/src/pipeline/mod.rs
  storage-provider/server/src/pipeline/types.rs
  storagext/lib/artifacts/metadata.scale
  storagext/lib/src/clients/storage_provider.rs
  storagext/lib/src/runtime/mod.rs
  storagext/lib/src/types/storage_provider.rs
Labels: ready for review, node-storage-provider

#624 feat: submit windowed posts repeatedly
  pallets/storage-provider/src/deadline.rs
  pallets/storage-provider/src/lib.rs
  pallets/storage-provider/src/tests/deadline.rs
  pallets/storage-provider/src/tests/mod.rs
  storage-provider/server/src/pipeline/mod.rs
Labels: enhancement, ready for review

#632 fix: use live sectors for proving partitions
  pallets/storage-provider/src/lib.rs
  storage-provider/server/src/pipeline/mod.rs
Labels: bug, ready for review

#626 docs: randomness research rfc
  rfcs/003-randomness.md
Labels: ready for review, rfc

#638 fix: add cancellation handling in proving
  storage-provider/server/src/pipeline/mod.rs
Labels: bug

#623 docs: retrieval research rfc
  rfcs/002-data-retrieval.md
Labels: ready for review, rfc

#629 docs: libp2p resolver rfc
  rfcs/001-libp2p-resolver.md
Labels: ready for review, rfc

#633 feat(randomness): use BABE's AuthorVRF as a randomness source
  Cargo.lock
  Cargo.toml
  docs/src/architecture/pallets/randomness.md
  pallets/market/src/mock.rs
  pallets/randomness/Cargo.toml
  pallets/randomness/src/inherent.rs
  pallets/randomness/src/lib.rs
  pallets/randomness/src/mock.rs
  pallets/randomness/src/tests.rs
  pallets/storage-provider/Cargo.toml
  pallets/storage-provider/src/lib.rs
  pallets/storage-provider/src/tests/mod.rs
  primitives/src/pallets.rs
  runtime/Cargo.toml
  runtime/src/configs/mod.rs
  runtime/src/lib.rs
  storagext/lib/artifacts/metadata.scale
  storagext/lib/src/clients/randomness.rs
Labels: ready for review

#642 fix(storage-provider): multiple sectors, multiple cache dirs
  lib/polka-storage-proofs/src/post/mod.rs
  storage-provider/client/src/commands/proofs.rs
  storage-provider/server/src/pipeline/mod.rs
  storage-provider/server/src/pipeline/types.rs
Labels: bug, ready for review

#643 fix(storagext): allow extrinsics to be submitted in parallel
  storagext/lib/src/runtime/client.rs
Labels: bug, ready for review

#645 fix: configure async backing properly
  runtime/src/configs/mod.rs
Labels: bug, ready for review

#646 fix(pallet-randomness): bring back the getter API
  .gitignore
  Cargo.lock
  Cargo.toml
  pallets/market/src/mock.rs
  pallets/randomness/src/lib.rs
  pallets/storage-provider/src/lib.rs
  pallets/storage-provider/src/tests/mod.rs
  primitives/src/randomness.rs
  runtime/src/configs/mod.rs
  storage-provider/server/Cargo.toml
  storage-provider/server/src/main.rs
Labels: ready for review

#648 fix: upgrade to polkadot2412 and use fork-aware txpool
  Cargo.lock
  Cargo.toml
  node/src/service.rs
  pallets/randomness/src/inherent.rs
  pallets/randomness/src/lib.rs
  runtime/src/configs/mod.rs
  runtime/src/lib.rs
  storagext/lib/artifacts/metadata.scale
  zombienet/local-testnet.toml
Labels: enhancement, ready for review

#649 fix: use subxt wait-for-success
  storagext/lib/src/runtime/client.rs
Labels: bug, enhancement, ready for review

#651 fix(storagext): losing transactions on reorg
  storage-provider/client/src/rpc_client.rs
  storagext/lib/src/runtime/client.rs
Labels: bug, ready for review

#656 feat(pallet-randomness): add benchmarks
  .gitattributes
  Cargo.lock
  node/benchmark_template.hbs
  pallets/randomness/Cargo.toml
  pallets/randomness/src/benchmarking.rs
  pallets/randomness/src/lib.rs
  pallets/randomness/src/mock.rs
  pallets/randomness/src/tests.rs
  pallets/randomness/src/weights.rs
  pallets/storage-provider/src/benchmarks.rs
  runtime/Cargo.toml
  runtime/src/benchmarks.rs
  runtime/src/configs/mod.rs
  runtime/src/lib.rs
Labels: ready for review
