Repository eigerco/polka-storage, pull requests merged in 2024-11, with the labels that each got.

#579 fix(market): batch published deals event
  cli/artifacts/metadata.scale
  cli/polka-storage-provider/server/src/rpc.rs
  cli/polka-storage/storagext/src/runtime/display/market.rs
  cli/polka-storage/storagext/src/runtime/mod.rs
  maat/tests/real_world.rs
  pallets/market/src/lib.rs
  pallets/market/src/test.rs
Labels: ready for review

#602 fix(docs): book link
  README.md
Labels: documentation, ready for review

#564 ci: automatically add hashes to the release
  .github/workflows/release.yaml
Labels: devops, ready for review

#605 fix: export runtime metadata
  cli/artifacts/metadata.scale
  node/src/service.rs
  runtime/src/apis.rs
  runtime/src/lib.rs
Labels: bug, ready for review

#607 fix(storage-provider-server): better error message for missing deal proposal
  cli/polka-storage-provider/server/src/rpc.rs
Labels: enhancement, ready for review

#608 docs: address polka forum feedback
  README.md
  docs/src/getting-started/demo-file-store.md
Labels: documentation, ready for review

#600 fix(maat): proofs
  Cargo.lock
  cli/polka-storage-provider/client/Cargo.toml
  cli/polka-storage-provider/client/src/commands/proofs.rs
  lib/polka-storage-proofs/src/porep/sealer.rs
  lib/polka-storage-proofs/src/post/mod.rs
  maat/generate_porep_proof.sh
  maat/tests/real_world.rs
  primitives/proofs/Cargo.toml
  primitives/proofs/src/types.rs
  runtime/src/configs/mod.rs
Labels: ready for review

#611 fix(storagext): use subxt retry mechanism instead of hand written
  Cargo.lock
  Justfile
  cli/polka-storage-provider/client/Cargo.toml
  cli/polka-storage-provider/common/Cargo.toml
  cli/polka-storage-provider/server/Cargo.toml
  cli/polka-storage/storagext-cli/Cargo.toml
  cli/polka-storage/storagext/Cargo.toml
  cli/polka-storage/storagext/src/runtime/client.rs
  docker/dockerfiles/polka-storage-node.Dockerfile
  docker/dockerfiles/storagext-cli.Dockerfile
  docs/src/getting-started/building/source.md
  maat/Cargo.toml
Labels: bug, ready for review

#613 chore: Replace static str errors
  Cargo.lock
  cli/polka-storage-provider/server/src/db.rs
  primitives/commitment/src/piece.rs
  primitives/proofs/Cargo.toml
  primitives/proofs/src/types.rs
Labels: ready for review

#609 feat(market): enable deal state retrieval
  .dockerignore
  docs/src/storagext-cli/market.md
  examples/rpc_publish.sh
  storagext/cli/src/cmd/market.rs
  storagext/lib/src/clients/market.rs
  storagext/lib/src/runtime/display/market.rs
Labels: ready for review

#614 fix(storage-provider-server): add deal validations & market account check
  .gitignore
  cli/polka-storage-provider/server/src/main.rs
  cli/polka-storage-provider/server/src/rpc.rs
  storagext/lib/src/types/market.rs
Labels: enhancement, ready for review

#612 feat(sp): Add batch events
  docs/src/architecture/pallets/storage-provider.md
  pallets/storage-provider/src/lib.rs
  pallets/storage-provider/src/tests/post_hook.rs
  pallets/storage-provider/src/tests/pre_commit_sector_hook.rs
  storagext/lib/artifacts/metadata.scale
  storagext/lib/src/runtime/display/storage_provider.rs
  storagext/lib/src/runtime/mod.rs
Labels: enhancement, ready for review, pallet-storage-provider

#593 feat: integrate submit_windowed_post with pallet proofs
  Cargo.lock
  cli/polka-storage-provider/client/src/commands/proofs.rs
  cli/polka-storage-provider/server/src/pipeline/mod.rs
  examples/rpc_publish.sh
  pallets/storage-provider/Cargo.toml
  pallets/storage-provider/src/lib.rs
  pallets/storage-provider/src/proofs.rs
  pallets/storage-provider/src/tests/mod.rs
  pallets/storage-provider/src/tests/submit_windowed_post.rs
  primitives/proofs/Cargo.toml
  primitives/proofs/src/lib.rs
  primitives/proofs/src/randomness.rs
  primitives/proofs/src/traits.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  storagext/cli/src/cmd/proofs.rs
  storagext/lib/Cargo.toml
  storagext/lib/artifacts/metadata.scale
  storagext/lib/src/clients/proofs.rs
  storagext/lib/src/clients/storage_provider.rs
Labels: ready for review

#618 docs: remove not-applicable confusing terms
  docs/src/glossary.md
Labels: documentation
