Repository eigerco/polka-storage, pull requests merged in 2025-01, with the labels that each got.

#663 chore(nix): change nix source & bump polkadot to 2412 and subxt-cli to 0.38
  flake.lock
  flake.nix
Labels: enhancement, ready for review

#658 feat: verify multiple partitions in pallets
  examples/deals.json
  examples/declare-fault.sh
  examples/fault-declaration.json
  examples/pre-commit-sector.json
  examples/prove-commit-sector.json
  examples/publish.sh
  examples/real-world-use-case-demo.sh
  examples/rpc_publish.sh
  examples/rpc_publish_multiple_sectors.sh
  examples/start_sp.sh
  examples/windowed-proof.json
  pallets/proofs/src/crypto/groth16.rs
  pallets/proofs/src/lib.rs
  pallets/proofs/src/porep/mod.rs
  pallets/proofs/src/post/mod.rs
  pallets/proofs/src/tests/post.rs
  pallets/randomness/src/lib.rs
  pallets/storage-provider/src/lib.rs
  pallets/storage-provider/src/proofs.rs
  pallets/storage-provider/src/tests/mod.rs
  primitives/src/lib.rs
  primitives/src/pallets.rs
  storage-provider/server/src/pipeline/mod.rs
  storagext/lib/artifacts/metadata.scale
  storagext/lib/src/types/storage_provider.rs
Labels: enhancement, ready for review

#657 feat(pallet-proofs): add benchmarks
  lib/polka-storage-proofs/src/groth16/mod.rs
  lib/polka-storage-proofs/src/groth16/substrate.rs
  pallets/market/src/mock.rs
  pallets/proofs/Cargo.toml
  pallets/proofs/src/benchmarking.rs
  pallets/proofs/src/lib.rs
  pallets/proofs/src/mock.rs
  pallets/proofs/src/weights.rs
  runtime/Cargo.toml
  runtime/src/benchmarks.rs
  runtime/src/configs/mod.rs
Labels: ready for review

#665 revert(09e27f6): change nix source & bump polkadot to 2412 and sub…
  flake.lock
  flake.nix
Labels: bug, ready for review

#662 feat: throttle parallel prove commits
  examples/rpc_publish_multiple_sectors.sh
  storage-provider/server/src/main.rs
  storage-provider/server/src/pipeline/mod.rs
Labels: enhancement, ready for review

#660 feat: implement file blockstore
  Cargo.lock
  Cargo.toml
  mater/lib/Cargo.toml
  mater/lib/src/lib.rs
  mater/lib/src/multicodec.rs
  mater/lib/src/stores/blockstore.rs
  mater/lib/src/stores/file.rs
  mater/lib/src/stores/mod.rs
  mater/lib/src/v2/index.rs
  mater/lib/src/v2/mod.rs
  mater/lib/src/v2/reader.rs
  mater/lib/src/v2/writer.rs
Labels: ready for review

#674 feat(polka-storage-provider-server): implement config file
  Cargo.lock
  Cargo.toml
  docs/src/storage-provider-cli/server.md
  examples/start_sp.sh
  primitives/src/proofs.rs
  storage-provider/server/Cargo.toml
  storage-provider/server/src/config.rs
  storage-provider/server/src/main.rs
Labels: ready for review, node-storage-provider

#673 fix: Add p2p node to rpc_publish
  examples/rpc_publish.sh
  examples/start_sp.sh
  storage-provider/server/src/config.rs
  storage-provider/server/src/p2p.rs
Labels: ready for review

#679 fix(primitives): extract PreCommitSectorInfo
  pallets/storage-provider/Cargo.toml
  pallets/storage-provider/src/lib.rs
  pallets/storage-provider/src/sector.rs
  pallets/storage-provider/src/tests/mod.rs
  pallets/storage-provider/src/tests/pre_commit_sectors.rs
  pallets/storage-provider/src/tests/prove_commit_sectors.rs
  primitives/Cargo.toml
  primitives/src/sector/mod.rs
  primitives/src/sector/number.rs
  primitives/src/sector/pre_commit.rs
  primitives/src/sector/size.rs
Labels: bug, ready for review, pallet-storage-provider

#681 feat: setup retrieval server and client
  Cargo.lock
  Cargo.toml
  mater/lib/src/lib.rs
  mater/lib/src/multicodec.rs
  mater/lib/tests/fixtures/car_v1/spaceglenda_wrapped.car
  mater/lib/tests/fixtures/car_v2/spaceglenda_wrapped.car
  storage-retrieval/cli/Cargo.toml
  storage-retrieval/cli/src/main.rs
  storage-retrieval/lib/Cargo.toml
  storage-retrieval/lib/README.md
  storage-retrieval/lib/examples/simple_server.rs
  storage-retrieval/lib/src/client.rs
  storage-retrieval/lib/src/lib.rs
  storage-retrieval/lib/src/server.rs
Labels: ready for review

#686 docs: Update docs to include p2p Peer ID and keys
  docs/src/storage-provider-cli/client/index.md
  docs/src/storage-provider-cli/server.md
Labels: documentation, ready for review

#689 fix: successfully_precommited_no_deals
  pallets/market/src/lib.rs
  pallets/storage-provider/src/lib.rs
  pallets/storage-provider/src/tests/pre_commit_sector_hook.rs
  pallets/storage-provider/src/tests/pre_commit_sectors.rs
  pallets/storage-provider/src/tests/prove_commit_sectors.rs
  primitives/src/pallets.rs
Labels: ready for review, pallet-market, node-storage-provider

#684 test: make prove commit work with maat
  Cargo.lock
  maat/Cargo.toml
  maat/tests/real_world.rs
  storage-provider/common/Cargo.toml
  storage-provider/common/src/lib.rs
  storage-provider/common/src/sector.rs
  storage-provider/server/src/pipeline/mod.rs
  storage-provider/server/src/pipeline/types.rs
Labels: ready for review, tech debt

#697 fix: Unlock pre commit desposit after proving
  pallets/market/src/lib.rs
  pallets/storage-provider/src/lib.rs
  pallets/storage-provider/src/tests/pre_commit_sector_hook.rs
  pallets/storage-provider/src/tests/prove_commit_sectors.rs
  primitives/src/pallets.rs
Labels: bug, ready for review

#700 fix(primitives): reduce cid feature set
  primitives/Cargo.toml
Labels: bug, ready for review

#685 feat: Add re-registration on expiry for p2p node
  docs/src/storage-provider-cli/server.md
  storage-provider/server/src/config.rs
  storage-provider/server/src/main.rs
  storage-provider/server/src/p2p/bootstrap.rs
  storage-provider/server/src/p2p/mod.rs
  storage-provider/server/src/p2p/register.rs
Labels: enhancement, ready for review

#701 fix(primitives): benchmark compilation issues
  primitives/src/proofs.rs
  primitives/src/sector/pre_commit.rs
Labels: bug, ready for review

#702 ci: run benchmarks
  .github/workflows/ci.yaml
Labels: devops, ready for review

#704 feat(pallet-storage-provider): extract ProveCommitSector
  pallets/storage-provider/src/lib.rs
  pallets/storage-provider/src/sector.rs
  pallets/storage-provider/src/tests/declare_faults.rs
  pallets/storage-provider/src/tests/post_hook.rs
  pallets/storage-provider/src/tests/pre_commit_sector_hook.rs
  pallets/storage-provider/src/tests/prove_commit_sectors.rs
  pallets/storage-provider/src/tests/submit_windowed_post.rs
  primitives/src/sector/mod.rs
  primitives/src/sector/prove_commit.rs
Labels: ready for review, pallet-storage-provider

#705 feat(pallet-market): implement benchmarks
  .github/workflows/ci.yaml
  Cargo.lock
  Cargo.toml
  node/Cargo.toml
  pallets/market/Cargo.toml
  pallets/market/src/benchmarking.rs
  pallets/market/src/lib.rs
  pallets/market/src/mock.rs
  pallets/market/src/test.rs
  pallets/market/src/weights.rs
  pallets/storage-provider/src/tests/mod.rs
  primitives/src/lib.rs
  primitives/src/sector/pre_commit.rs
  runtime/Cargo.toml
  runtime/src/benchmarks.rs
  runtime/src/configs/mod.rs
  storagext/lib/Cargo.toml
Labels: ready for review, pallet-market

#699 refactor: PoSt e2e test
  Cargo.lock
  maat/src/lib.rs
  maat/tests/real_world.rs
  pallets/market/src/lib.rs
  pallets/market/src/test.rs
  storage-provider/common/src/deadline.rs
  storage-provider/common/src/lib.rs
  storage-provider/server/Cargo.toml
  storage-provider/server/src/pipeline/mod.rs
Labels: bug, enhancement, ready for review

#707 fix(storagext): update .scale & api accordingly
  storagext/lib/artifacts/metadata.scale
  storagext/lib/src/runtime/display/storage_provider.rs
  storagext/lib/src/runtime/mod.rs
  storagext/lib/src/types/storage_provider.rs
Labels: bug, ready for review

#706 feat: mater car reader read_block_metadata
  mater/lib/src/async_varint.rs
  mater/lib/src/cid.rs
  mater/lib/src/lib.rs
  mater/lib/src/multicodec.rs
  mater/lib/src/stores/file.rs
  mater/lib/src/v1/mod.rs
  mater/lib/src/v1/reader.rs
  mater/lib/src/v2/index.rs
  mater/lib/src/v2/reader.rs
Labels: ready for review

#710 fix: zero padding reader incomplete reads
  lib/polka-storage-proofs/src/zero_reader.rs
Labels: bug, ready for review

#711 fix: update polkadot to 2412 and subxt-cli to 0.38.
  flake.lock
  flake.nix
Labels: enhancement, ready for review

#712 feat(storage-provider): add status RPC
  Justfile
  examples/rpc_publish.sh
  examples/start_sp.sh
  storage-provider/client/src/commands/mod.rs
  storage-provider/common/src/rpc/mod.rs
  storage-provider/server/src/rpc.rs
Labels: enhancement, ready for review, node-storage-provider

#696 feat: Add p2p resolver example
  storage-provider/client/Cargo.toml
  storage-provider/client/examples/peer-resolver.rs
Labels: enhancement, ready for review

#708 feat: add support for 8MiB sector size
  Cargo.lock
  examples/big_file_184k.car
  lib/polka-storage-proofs/src/porep/mod.rs
  lib/polka-storage-proofs/src/porep/sealer.rs
  lib/polka-storage-proofs/src/post/mod.rs
  maat/tests/real_world.rs
  pallets/proofs/src/porep/config.rs
  pallets/proofs/src/porep/mod.rs
  primitives/src/proofs.rs
  storage-provider/client/src/commands/proofs.rs
  storage-provider/common/Cargo.toml
  storage-provider/common/src/commp.rs
  storage-provider/common/src/sector.rs
  storage-provider/server/src/storage.rs
  storagext/cli/src/cmd/storage_provider.rs
  storagext/lib/artifacts/metadata.scale
Labels: enhancement, ready for review
