Repository eigerco/polka-storage, pull requests merged in 2025-05, with the labels that each got.

#843 refactor(sp): Move `assign_proving_period_offset` to primitives
  pallets/storage-provider/src/lib.rs
  pallets/storage-provider/src/proofs.rs
  primitives/src/proofs.rs
Labels: ready for review

#844 test(sp): Use runtime benchmark testnet parameters in SP test benchmarks
  pallets/storage-provider/benchmarks/src/mock.rs
  pallets/storage-provider/src/lib.rs
Labels: ready for review

#839 fix: public p2p addreses
  Justfile
  node/src/cli.rs
  node/src/command.rs
  node/src/rpc.rs
  node/src/service/p2p/bootstrap.rs
  node/src/service/p2p/mod.rs
  primitives-p2p/src/request_response/services.rs
  primitives/src/test_data.rs
  runtime/src/configs/mod.rs
  storage-provider/server/src/config.rs
  storage-provider/server/src/main.rs
Labels: ready for review

#847 refactor(primitives): Refactor `test_data` module
  pallets/market/benchmarks/src/benchmarking.rs
  pallets/storage-provider/benchmarks/src/benchmarking.rs
  primitives/src/test_data/benchmark_data.rs
  primitives/src/test_data/mod.rs
  primitives/src/test_data/sector_data.rs
  primitives/src/test_data/storage_provider_data.rs
  storage-provider/client/src/commands/proofs.rs
Labels: ready for review

#851 test(market): Use runtime benchmark testnet parameters in market test benchmarks
  pallets/market/benchmarks/src/mock.rs
Labels: ready for review

#857 fix: sector sealing and piece adding
  storage-provider/server/src/db.rs
  storage-provider/server/src/pipeline/add_piece.rs
  storage-provider/server/src/pipeline/mod.rs
Labels: ready for review

#855 docs: add delia dapp docs
  docs/src/SUMMARY.md
  docs/src/architecture/delia.md
  docs/src/images/architecture/delia-connect.png
  docs/src/images/architecture/delia-full.png
  docs/src/images/architecture/storage-provider-connect.png
Labels: documentation

#856 feat(primitives): Add structs for representing a test timeline
  pallets/market/benchmarks/src/benchmarking.rs
  pallets/storage-provider/benchmarks/src/benchmarking.rs
  primitives/src/test_data/absolute_block_number.rs
  primitives/src/test_data/benchmark_data.rs
  primitives/src/test_data/deal_timeline.rs
  primitives/src/test_data/mod.rs
  primitives/src/test_data/relative_block_number.rs
  primitives/src/test_data/sector_timeline.rs
  storage-provider/client/Cargo.toml
  storage-provider/client/src/commands/proofs.rs
  test-fixtures/proofs/8MiB/0.sector.proof.porep.scale
  test-fixtures/proofs/8MiB/0.sector.proof.post.scale
Labels: ready for review

#859 docs: Improve pallet documentation
  docs/src/architecture/pallets/faucet.md
  docs/src/architecture/pallets/index.md
  docs/src/architecture/pallets/market.md
  docs/src/architecture/pallets/randomness.md
  docs/src/introduction.md
Labels: ready for review

#860 test(sp): Benchmark PoSt with 1GiB sector size
  pallets/storage-provider/benchmarks/src/benchmarking.rs
  pallets/storage-provider/src/lib.rs
  primitives/src/test_data/benchmark_data.rs
  test-fixtures/proofs/1GiB/0.sector.proof.porep.scale
  test-fixtures/proofs/1GiB/0.sector.proof.post.scale
Labels: ready for review

#861 fix(sp): remove cli args
  Cargo.lock
  storage-provider/common/Cargo.toml
  storage-provider/common/src/config/sealing.rs
  storage-provider/server/Cargo.toml
  storage-provider/server/src/config.rs
  storage-provider/server/src/main.rs
Labels: bug, ready for review

#862 feat(sp): add external addresses manually
  storage-provider/server/src/config.rs
  storage-provider/server/src/main.rs
  storage-provider/server/src/p2p/mod.rs
Labels: ready for review

#869 chore: separate storage pallet logic to the modules
  pallets/storage-provider/src/deadline/mod.rs
  pallets/storage-provider/src/dispatchables/declare_faults.rs
  pallets/storage-provider/src/dispatchables/declare_faults_recovered.rs
  pallets/storage-provider/src/dispatchables/mod.rs
  pallets/storage-provider/src/dispatchables/pre_commit_sectors.rs
  pallets/storage-provider/src/dispatchables/prove_commit_sectors.rs
  pallets/storage-provider/src/dispatchables/register_storage_provider.rs
  pallets/storage-provider/src/dispatchables/submit_windowed_post.rs
  pallets/storage-provider/src/dispatchables/terminate_sectors.rs
  pallets/storage-provider/src/hooks/check_deadlines.rs
  pallets/storage-provider/src/hooks/check_precommited_sectors.rs
  pallets/storage-provider/src/hooks/mod.rs
  pallets/storage-provider/src/lib.rs
  pallets/storage-provider/src/storage_provider.rs
Labels: ready for review

#867 feat: log config on server sturtup
  storage-provider/server/src/main.rs
Labels: ready for review
