Repository eigerco/polka-storage, pull requests merged in 2025-03, with the labels that each got.

#791 fix: 1GiB sectors porep & post key
  .gitattributes
  .gitignore
  examples/1GiB.porep.vk
  examples/1GiB.porep.vk.scale
  examples/1GiB.post.vk
  examples/1GiB.post.vk.scale
  lib/polka-storage-proofs/Cargo.toml
  lib/polka-storage-proofs/src/groth16/mod.rs
  lib/polka-storage-proofs/src/groth16/std.rs
  lib/polka-storage-proofs/src/groth16/substrate.rs
  pallets/proofs/src/lib.rs
Labels: bug, ready for review

#788 fix(sp-server): cancel & stop tasks on failure
  storage-provider/server/Cargo.toml
  storage-provider/server/src/main.rs
  storage-provider/server/src/p2p/mod.rs
  storage-provider/server/src/pipeline/mod.rs
Labels: enhancement

#792 fix: Storagext deal param types
  storagext/lib/artifacts/metadata.scale
  storagext/lib/src/clients/market.rs
  storagext/lib/src/runtime/display/market.rs
  storagext/lib/src/runtime/mod.rs
  storagext/lib/src/types/market.rs
Labels: enhancement, ready for review

#794 fix: set 1GiB verifying keys in Genesis Config
  .github/workflows/ci.yaml
  Cargo.lock
  Justfile
  docker/dockerfiles/polka-storage-node.Dockerfile
  lib/polka-storage-proofs/Cargo.toml
  lib/polka-storage-proofs/src/groth16/mod.rs
  lib/polka-storage-proofs/src/groth16/std.rs
  lib/polka-storage-proofs/src/groth16/substrate.rs
  node/Cargo.toml
  node/src/chain_spec.rs
  pallets/market/Cargo.toml
  pallets/proofs/Cargo.toml
  pallets/proofs/src/lib.rs
  pallets/proofs/src/mock.rs
  pallets/storage-provider/Cargo.toml
  primitives/src/proofs.rs
Labels: bug, ready for review

#797 feat(sp-server): Add deal param validation
  examples/rpc_publish.sh
  examples/start_sp.sh
  storage-provider/server/src/rpc.rs
  storagext/cli/src/cmd/market.rs
  storagext/lib/src/runtime/display/market.rs
Labels: enhancement, ready for review

#800 feat: Add deal param RPC endpoints
  storage-provider/common/src/rpc/mod.rs
  storage-provider/server/src/rpc.rs
  storagext/cli/src/cmd/market.rs
  storagext/lib/src/clients/market.rs
  storagext/lib/src/types/market.rs
Labels: enhancement, ready for review

#802 refactor: add genesis config to market and proofs pallet
  Justfile
  examples/8MiB.porep.vk
  examples/8MiB.porep.vk.scale
  examples/8MiB.post.vk
  examples/8MiB.post.vk.scale
  examples/rpc_publish.sh
  examples/start_sp.sh
  examples/start_sps.sh
  lib/polka-storage-proofs/src/groth16/substrate.rs
  maat/tests/real_world.rs
  node/src/chain_spec.rs
  pallets/market/src/lib.rs
Labels: enhancement, ready for review

#803 fix(sp-server): remove delia-specific APIs
  storage-provider/server/Cargo.toml
  storage-provider/server/src/storage.rs
Labels: ready for review

#804 fix(node): multiaddr default & validation
  flake.nix
  node/src/cli.rs
  node/src/command.rs
  zombienet/local-testnet.toml
Labels: ready for review

#806 feat(storage_provider_server): add ws libp2p support
  node/src/cli.rs
  primitives/src/p2p.rs
  storage-provider/server/Cargo.toml
  storage-provider/server/src/config.rs
  storage-provider/server/src/indexer/mod.rs
  storage-provider/server/src/main.rs
  storage-provider/server/src/p2p/error.rs
  storage-provider/server/src/p2p/mod.rs
  storage-provider/server/src/p2p/swarm.rs
Labels: ready for review

#807 feat(node/sp/fetch): make req/resp protocol length-prefixed
  Cargo.lock
  Cargo.toml
  examples/start_sp.sh
  flake.nix
  lib/libp2p-length-prefix-codec/Cargo.toml
  lib/libp2p-length-prefix-codec/src/cbor.rs
  lib/libp2p-length-prefix-codec/src/lib.rs
  node/Cargo.toml
  node/src/service/p2p/bootstrap.rs
  node/src/service/p2p/mod.rs
  primitives/src/p2p.rs
  storage-fetch/Cargo.toml
  storage-fetch/src/main.rs
  storage-fetch/src/p2p/mod.rs
  storage-provider/server/Cargo.toml
  storage-provider/server/src/p2p/mod.rs
  storage-provider/server/src/rpc.rs
Labels: ready for review

#808 fix(primitives-p2p): split off p2p module
  Cargo.lock
  Cargo.toml
  node/Cargo.toml
  node/src/cli.rs
  node/src/service/p2p/bootstrap.rs
  primitives-p2p/Cargo.toml
  primitives-p2p/src/lib.rs
  primitives-p2p/src/request_response/bootstrap.rs
  primitives-p2p/src/request_response/mod.rs
  primitives-p2p/src/request_response/storage_provider.rs
  primitives/Cargo.toml
  primitives/src/lib.rs
  storage-fetch/Cargo.toml
  storage-fetch/src/p2p/resolvers.rs
  storage-provider/client/Cargo.toml
  storage-provider/client/examples/peer-resolver.rs
  storage-provider/client/src/main.rs
  storage-provider/server/Cargo.toml
  storage-provider/server/src/config.rs
  storage-provider/server/src/p2p/mod.rs
Labels: ready for review

#811 bump: beetswap 0.4.1
  Cargo.lock
  Cargo.toml
Labels: ready for review

#812 fix: fetch randomness from chain for batch verification
  pallets/market/benchmarks/src/mock.rs
  pallets/proofs/Cargo.toml
  pallets/proofs/src/crypto/groth16.rs
  pallets/proofs/src/lib.rs
  pallets/proofs/src/mock.rs
  pallets/proofs/src/porep/mod.rs
  pallets/proofs/src/post/mod.rs
  runtime/src/configs/mod.rs
Labels: enhancement, ready for review

#813 fix: PoSt partition batching
  lib/polka-storage-proofs/src/post/mod.rs
  pallets/proofs/src/lib.rs
  pallets/proofs/src/porep/mod.rs
  pallets/proofs/src/post/mod.rs
  pallets/proofs/src/tests/mod.rs
  pallets/proofs/src/tests/porep.rs
  pallets/proofs/src/tests/post.rs
  pallets/storage-provider/src/lib.rs
  pallets/storage-provider/src/proofs.rs
  primitives/src/lib.rs
  primitives/src/pallets.rs
  primitives/src/proofs.rs
  primitives/src/sector/prove_commit.rs
  storage-provider/common/src/deadline.rs
  storagext/lib/artifacts/metadata.scale
Labels: bug, ready for review
