Repository eigerco/polka-storage, pull requests merged in 2025-04, with the labels that each got.

#816 Refactor storage-provider-client
  storage-provider/client/src/commands/proofs.rs
Labels: ready for review

#814 fix: set mainnet values for 1GiB sectors
  runtime/src/configs/mod.rs
Labels: enhancement, ready for review

#815 docs(book): update book storagext-cli chapter & add polka-fetch
  docs/src/SUMMARY.md
  docs/src/architecture/pallets/proofs.md
  docs/src/architecture/pallets/storage-provider.md
  docs/src/architecture/polka-storage-provider-server.md
  docs/src/glossary.md
  docs/src/polka-fetch/index.md
  docs/src/storagext-cli/market.md
  docs/src/storagext-cli/proofs.md
  docs/src/storagext-cli/storage-provider.md
  docs/src/storagext-cli/system.md
  storagext/cli/src/cmd/proofs.rs
Labels: ready for review

#819 fix: change polkastore address and change keys
  Justfile
Labels: bug, ready for review

#822 fix(maat): Fix collator command line arg
  maat/src/lib.rs
Labels: ready for review

#821 feat(sp/node): resolve PeerId -> Multiaddr
  Cargo.lock
  examples/start_sps.sh
  node/Cargo.toml
  node/src/chain_spec.rs
  node/src/service/p2p/bootstrap.rs
  node/src/service/p2p/mod.rs
  primitives-p2p/src/request_response/bootstrap.rs
  storage-provider/server/Cargo.toml
  storage-provider/server/src/p2p/mod.rs
  zombienet/local-testnet.toml
Labels: ready for review

#823 feat(sp): add services req/resp protocol
  Cargo.lock
  primitives-p2p/Cargo.toml
  primitives-p2p/src/lib.rs
  primitives-p2p/src/request_response/mod.rs
  primitives-p2p/src/request_response/services.rs
  storage-provider/server/src/main.rs
  storage-provider/server/src/p2p/mod.rs
Labels: ready for review

#818 test(primitives): Extract commonalities from market and storage-provider pallet benchmarks, and use real proof data
  Cargo.lock
  Cargo.toml
  Justfile
  examples/1.sector.proof.porep.scale
  examples/1.sector.proof.post.scale
  examples/8MiB.porep.vk
  examples/8MiB.porep.vk.scale
  examples/8MiB.post.vk
  examples/8MiB.post.vk.scale
  lib/polka-storage-proofs/src/groth16/std.rs
  lib/polka-storage-proofs/src/groth16/substrate.rs
  maat/tests/real_world.rs
  node/src/chain_spec.rs
  pallets/market/benchmarks/src/benchmarking.rs
  pallets/market/benchmarks/src/mock.rs
  pallets/market/benchmarks/src/test.rs
  pallets/market/src/deal_parameters.rs
  pallets/market/src/lib.rs
  pallets/proofs/src/tests/mod.rs
  pallets/storage-provider/benchmarks/Cargo.toml
  pallets/storage-provider/benchmarks/src/benchmarking.rs
  pallets/storage-provider/benchmarks/src/benchmarking/accounts.rs
  pallets/storage-provider/benchmarks/src/benchmarking/deal_proposals.rs
  pallets/storage-provider/benchmarks/src/benchmarking/mod.rs
  pallets/storage-provider/benchmarks/src/mock.rs
  pallets/storage-provider/benchmarks/src/pallet.rs
  pallets/storage-provider/src/lib.rs
  pallets/storage-provider/src/tests/mod.rs
  pallets/storage-provider/src/tests/pre_commit_sectors.rs
  pallets/storage-provider/src/tests/prove_commit_sectors.rs
  primitives/Cargo.toml
  primitives/src/configs.rs
  primitives/src/deals/active_deal_state.rs
  primitives/src/deals/client_deal_proposal.rs
  primitives/src/deals/deal_proposal.rs
  primitives/src/deals/deal_state.rs
  primitives/src/deals/mod.rs
  primitives/src/lib.rs
  primitives/src/pallets.rs
  primitives/src/test_data.rs
  runtime/src/configs/mod.rs
  storage-provider/client/Cargo.toml
  storage-provider/client/src/commands/mod.rs
  storage-provider/client/src/commands/proofs.rs
  test-fixtures/keys/1GiB.porep.vk
  test-fixtures/keys/1GiB.porep.vk.scale
  test-fixtures/keys/1GiB.post.vk
  test-fixtures/keys/1GiB.post.vk.scale
  test-fixtures/keys/8MiB.porep.vk
  test-fixtures/keys/8MiB.porep.vk.scale
  test-fixtures/keys/8MiB.post.vk
  test-fixtures/keys/8MiB.post.vk.scale
  test-fixtures/proofs/1GiB/0.sector.proof.porep.scale
  test-fixtures/proofs/8MiB/0.sector.proof.porep.scale
Labels: ready for review

#831 fix: Move constants back to pallets and fix module references
  Cargo.lock
  maat/tests/real_world.rs
  pallets/market/benchmarks/src/mock.rs
  pallets/market/benchmarks/src/test.rs
  pallets/market/src/lib.rs
  pallets/storage-provider/benchmarks/src/mock.rs
  pallets/storage-provider/src/lib.rs
  pallets/storage-provider/src/tests/mod.rs
  primitives/src/configs.rs
  primitives/src/test_data.rs
  runtime/src/configs/mod.rs
  storagext/lib/artifacts/metadata.scale
  storagext/lib/src/clients/market.rs
  storagext/lib/src/runtime/display/market.rs
  storagext/lib/src/runtime/mod.rs
  storagext/lib/src/types/market.rs
  storagext/lib/src/types/storage_provider.rs
Labels: ready for review

#830 fix(mater): use u32 instead of i32 in the indexes
  mater/lib/src/v2/index.rs
Labels: ready for review

#826 test(sp): Refactor benchmarks
  pallets/storage-provider/benchmarks/src/benchmarking.rs
Labels: ready for review

#828 test(sp): Benchmark `declare_faults`
  Cargo.lock
  pallets/storage-provider/benchmarks/Cargo.toml
  pallets/storage-provider/benchmarks/src/benchmarking.rs
  pallets/storage-provider/src/lib.rs
Labels: ready for review

#833 test(sp): Use assert_ok_sp in all benchmarks
  pallets/storage-provider/benchmarks/src/benchmarking.rs
Labels: ready for review

#834 test(sp): Benchmark `declare_faults_recovered`
  pallets/storage-provider/benchmarks/src/benchmarking.rs
Labels: ready for review

#836 fix: adjust deal params for frontend
  examples/start_sp.sh
  runtime/src/configs/mod.rs
  storage-provider/server/src/rpc.rs
  storagext/lib/artifacts/metadata.scale
Labels: bug, ready for review
