Repository eigerco/polka-storage, pull requests merged in 2025-02, with the labels that each got.

#719 feat: resolve rococo-runtime error
  flake.lock
  flake.nix
  maat/src/lib.rs
  zombienet/local-kube-testnet.toml
  zombienet/local-testnet.toml
  zombienet/rococo-local.json
Labels: ready for review

#721 feat(maat): add caching for porep/post params
  maat/tests/real_world.rs
Labels: enhancement, ready for review

#713 rfc: Add P2P info exchange
  rfcs/004-p2p-information-exchange.md
Labels: ready for review, rfc

#730 fix: polkadot nix build fails due to clang std=c++17 on MacOS
  flake.nix
Labels: bug

#731 fix(storage-provider): wait for deadline end on empty partition
  pallets/storage-provider/src/lib.rs
  primitives/src/pallets.rs
  storage-provider/common/src/deadline.rs
  storagext/lib/artifacts/metadata.scale
Labels: ready for review

#734 fix: Add required = false to p2p cli args
  storage-provider/server/src/config.rs
Labels: ready for review

#732 feat(storage-provider): add size-based multi sector
  Justfile
  storage-provider/common/src/sector.rs
  storage-provider/server/src/db.rs
  storage-provider/server/src/main.rs
  storage-provider/server/src/pipeline/mod.rs
  storage-provider/server/src/rpc.rs
  storagext/lib/src/clients/storage_provider.rs
Labels: ready for review

#735 feat(storage-provider): add sealing configuration
  Cargo.lock
  storage-provider/common/Cargo.toml
  storage-provider/common/src/config/mod.rs
  storage-provider/common/src/config/sealing.rs
  storage-provider/common/src/lib.rs
  storage-provider/common/src/rpc/mod.rs
  storage-provider/server/Cargo.toml
  storage-provider/server/src/config.rs
  storage-provider/server/src/main.rs
  storage-provider/server/src/pipeline/mod.rs
Labels: ready for review

#736 fix(storage-provider): make default body limit max sector size
  storage-provider/server/src/rpc.rs
  storage-provider/server/src/storage.rs
Labels: ready for review

#717 feat: support 512 & 1GiB with huge refactors
  Cargo.lock
  lib/polka-storage-proofs/src/porep/mod.rs
  lib/polka-storage-proofs/src/porep/sealer.rs
  lib/polka-storage-proofs/src/post/mod.rs
  pallets/proofs/src/porep/config.rs
  pallets/randomness/src/lib.rs
  pallets/storage-provider/src/lib.rs
  pallets/storage-provider/src/sector.rs
  primitives/src/proofs.rs
  primitives/src/sector/size.rs
  storage-provider/client/Cargo.toml
  storage-provider/client/src/commands/proofs.rs
  storage-provider/common/Cargo.toml
  storage-provider/common/src/deadline.rs
  storage-provider/common/src/sector.rs
  storagext/lib/artifacts/metadata.scale
Labels: enhancement, ready for review

#737 fix(storage-provider): concurrency & logic bugs in add_piece
  examples/start_sp.sh
  storage-provider/common/src/config/sealing.rs
  storage-provider/common/src/sector.rs
  storage-provider/server/src/main.rs
  storage-provider/server/src/pipeline/mod.rs
Labels: ready for review

#727 feat: Move bootstrap node into collator
  Cargo.lock
  Justfile
  docs/src/storage-provider-cli/server.md
  examples/rpc_publish.sh
  examples/start_sp.sh
  maat/Cargo.toml
  maat/src/lib.rs
  node/Cargo.toml
  node/src/cli.rs
  node/src/command.rs
  node/src/service/mod.rs
  node/src/service/p2p/bootstrap.rs
  node/src/service/p2p/mod.rs
  primitives/Cargo.toml
  primitives/src/lib.rs
  primitives/src/p2p.rs
  storage-provider/server/Cargo.toml
  storage-provider/server/src/config.rs
  storage-provider/server/src/main.rs
  storage-provider/server/src/p2p/mod.rs
  zombienet/local-kube-testnet.toml
  zombienet/local-testnet.toml
Labels: enhancement, ready for review

#733 feat(storage-provider): add time-based sector sealing
  examples/start_sp.sh
  storage-provider/common/src/config/sealing.rs
  storage-provider/server/src/db.rs
  storage-provider/server/src/main.rs
  storage-provider/server/src/pipeline/mod.rs
  storage-provider/server/src/pipeline/types.rs
Labels: ready for review

#745 feat: configure feature flags for OpenCL and CUDA
  Cargo.lock
  Cargo.toml
  Justfile
  docs/src/getting-started/building/source.md
  lib/polka-storage-proofs/Cargo.toml
  maat/Cargo.toml
  storage-provider/client/Cargo.toml
  storage-provider/server/Cargo.toml
Labels: enhancement, ready for review

#748 fix: post proof batching
  Cargo.lock
  storage-provider/common/Cargo.toml
  storage-provider/common/src/deadline.rs
  storage-provider/server/src/pipeline/mod.rs
  storagext/lib/src/types/storage_provider.rs
Labels: ready for review

#753 feat(mater): tree-aware content extraction
  Cargo.lock
  mater/cli/Cargo.toml
  mater/cli/src/convert.rs
  mater/cli/src/error.rs
  mater/cli/src/extract.rs
  mater/cli/src/main.rs
  mater/lib/src/async_varint.rs
  mater/lib/src/file_reader.rs
  mater/lib/src/lib.rs
  mater/lib/src/unixfs/mod.rs
  mater/lib/src/v1/mod.rs
  mater/lib/src/v1/reader.rs
  mater/lib/src/v2/index.rs
  mater/lib/src/v2/reader.rs
Labels: ready for review

#754 fix: set proper key path and tempdir for collator key
  maat/src/lib.rs
  maat/tests/real_world.rs
Labels: bug, ready for review

#752 fix: support multiple partitions in PoRep
  pallets/market/src/benchmarking.rs
  pallets/proofs/src/lib.rs
  pallets/proofs/src/porep/config.rs
  pallets/proofs/src/porep/mod.rs
  pallets/proofs/src/post/mod.rs
  pallets/proofs/src/tests/porep.rs
  pallets/storage-provider/src/lib.rs
  pallets/storage-provider/src/tests/declare_faults.rs
  pallets/storage-provider/src/tests/post_hook.rs
  pallets/storage-provider/src/tests/pre_commit_sector_hook.rs
  pallets/storage-provider/src/tests/prove_commit_sectors.rs
  pallets/storage-provider/src/tests/submit_windowed_post.rs
  primitives/src/pallets.rs
  primitives/src/proofs.rs
  primitives/src/sector/prove_commit.rs
  storage-provider/common/src/sector.rs
  storagext/lib/artifacts/metadata.scale
  storagext/lib/src/types/storage_provider.rs
Labels: enhancement, ready for review

#761 feat(mater-cli): add support for stdin input
  mater/cli/Cargo.toml
  mater/cli/src/convert.rs
  mater/cli/src/extract.rs
  mater/cli/src/main.rs
  mater/lib/src/lib.rs
Labels: ready for review

#688 feat: sector indexing and data retrieval
  Cargo.lock
  mater/lib/src/cid.rs
  mater/lib/src/lib.rs
  storage-provider/common/src/sector.rs
  storage-provider/server/Cargo.toml
  storage-provider/server/src/config.rs
  storage-provider/server/src/indexer/local_index_directory/mod.rs
  storage-provider/server/src/indexer/local_index_directory/rdb.rs
  storage-provider/server/src/indexer/mod.rs
  storage-provider/server/src/local_index_directory/rdb_ext.rs
  storage-provider/server/src/main.rs
  storage-provider/server/src/pipeline/mod.rs
  storage-provider/server/src/retrieval/blockstore.rs
  storage-provider/server/src/retrieval/mod.rs
  storage-provider/server/tests/fixtures/spaceglenda_wrapped_v2.car
  storage-retrieval/lib/examples/simple_server.rs
  storage-retrieval/lib/src/server.rs
Labels: ready for review

#740 feat(storage-provider): benchmark register & pre_commit
  .github/workflows/ci.yaml
  Cargo.lock
  Cargo.toml
  Justfile
  pallets/storage-provider/benchmarks/Cargo.toml
  pallets/storage-provider/benchmarks/src/benchmarking/accounts.rs
  pallets/storage-provider/benchmarks/src/benchmarking/deal_proposals.rs
  pallets/storage-provider/benchmarks/src/benchmarking/mod.rs
  pallets/storage-provider/benchmarks/src/lib.rs
  pallets/storage-provider/benchmarks/src/mock.rs
  pallets/storage-provider/benchmarks/src/pallet.rs
  pallets/storage-provider/src/benchmarks.rs
  pallets/storage-provider/src/lib.rs
  runtime/Cargo.toml
  runtime/src/benchmarks.rs
  runtime/src/lib.rs
Labels: ready for review

#762 fix: add support for multiple proof types at the network level
  Justfile
  examples/start_sp.sh
  lib/polka-storage-proofs/src/groth16/mod.rs
  maat/tests/real_world.rs
  pallets/proofs/src/benchmarking.rs
  pallets/proofs/src/lib.rs
  pallets/proofs/src/tests/porep.rs
  pallets/proofs/src/tests/post.rs
  pallets/proofs/src/weights.rs
  primitives/src/proofs.rs
  storagext/cli/src/cmd/proofs.rs
  storagext/lib/Cargo.toml
  storagext/lib/artifacts/metadata.scale
  storagext/lib/src/clients/proofs.rs
Labels: ready for review

#765 fix(mater): remove unnecessary PartialNode abstraction
  mater/lib/src/file_reader.rs
Labels: ready for review

#764 fix(pipeline): precommit scheduling
  storage-provider/server/src/pipeline/add_piece.rs
Labels: ready for review

#768 chore: VS Code settings
  .gitignore
  .vscode/settings.default.json
  .vscode/settings.json
Labels: ready for review

#767 fix(mater): add tests to the extractor
  mater/lib/src/file_reader.rs
Labels: ready for review

#769 ci: Run CI on all 'ready-to-review' PR commits
  .github/workflows/ci.yaml
Labels: ready for review

#763 rfc: Add deal parameters
  rfcs/005-deal-parameters.md
  rfcs/images/deal-flow.png
Labels: ready for review, rfc

#775 fix(mater): remove the bounds on get_inner_mut
  mater/lib/src/v2/writer.rs
Labels: ready for review

#773 feat(mater): remove filestore abstraction in favor of blockwriter
  mater/cli/src/convert.rs
  mater/lib/benches/benchmark.rs
  mater/lib/src/file_reader.rs
  mater/lib/src/lib.rs
  mater/lib/src/stores/blockstore.rs
  mater/lib/src/stores/filestore.rs
  mater/lib/src/stores/mod.rs
  mater/lib/tests/fixtures/original/zero
  storage-provider/server/src/storage.rs
Labels: ready for review

#774 feat(mater): add mater::ReadOnlyBlockstore
  mater/lib/src/cid.rs
  mater/lib/src/file_reader.rs
  mater/lib/src/lib.rs
  mater/lib/src/stores/file.rs
  mater/lib/src/stores/mod.rs
  mater/lib/src/v1/mod.rs
  storage-retrieval/cli/src/main.rs
  storage-retrieval/lib/examples/simple_server.rs
Labels: ready for review

#777 feat(mater): replace the Reader/Writer structs with traits
  mater/lib/src/file_reader.rs
  mater/lib/src/ipld.rs
  mater/lib/src/lib.rs
  mater/lib/src/stores/blockstore.rs
  mater/lib/src/stores/file.rs
  mater/lib/src/v1/mod.rs
  mater/lib/src/v1/reader.rs
  mater/lib/src/v1/writer.rs
  mater/lib/src/v2/index.rs
  mater/lib/src/v2/mod.rs
  mater/lib/src/v2/reader.rs
  mater/lib/src/v2/writer.rs
  storage-provider/client/src/commands/proofs.rs
  storage-provider/server/src/indexer/mod.rs
  storage-provider/server/src/retrieval/blockstore.rs
Labels: ready for review

#780 fix(storagext): track nonces per-account
  storagext/lib/src/runtime/client.rs
Labels: ready for review

#779 feat(mater/fetch): add ReadWriteBlockstore
  Cargo.lock
  Cargo.toml
  mater/cli/src/convert.rs
  mater/cli/src/extract.rs
  mater/lib/Cargo.toml
  mater/lib/benches/benchmark.rs
  mater/lib/src/convert/mod.rs
  mater/lib/src/convert/reader.rs
  mater/lib/src/convert/writer.rs
  mater/lib/src/lib.rs
  mater/lib/src/stores/blockstore.rs
  mater/lib/src/stores/file.rs
  mater/lib/src/v1/mod.rs
  mater/lib/src/v2/mod.rs
  storage-provider/server/src/storage.rs
  storage-retrieval/cli/src/main.rs
  storage-retrieval/lib/src/client.rs
Labels: ready for review

#778 feat: Add deal parameters
  Justfile
  docs/src/architecture/pallets/market.md
  pallets/market/Cargo.toml
  pallets/market/src/benchmarking.rs
  pallets/market/src/deal_parameters.rs
  pallets/market/src/error.rs
  pallets/market/src/lib.rs
  pallets/market/src/test.rs
  pallets/market/src/weights.rs
  storagext/cli/src/cmd/market.rs
  storagext/lib/artifacts/metadata.scale
  storagext/lib/src/clients/market.rs
  storagext/lib/src/runtime/display/market.rs
  storagext/lib/src/runtime/mod.rs
  storagext/lib/src/types/market.rs
Labels: enhancement, ready for review

#785 feat: refactor p2p node & merge retrieval functionality
  Cargo.lock
  Cargo.toml
  storage-fetch/Cargo.toml
  storage-fetch/src/client.rs
  storage-fetch/src/main.rs
  storage-fetch/src/p2p.rs
  storage-provider/server/Cargo.toml
  storage-provider/server/src/config.rs
  storage-provider/server/src/main.rs
  storage-provider/server/src/p2p/blockstore/chaos.rs
  storage-provider/server/src/p2p/blockstore/mod.rs
  storage-provider/server/src/p2p/blockstore/pieces.rs
  storage-provider/server/src/p2p/error.rs
  storage-provider/server/src/p2p/mod.rs
  storage-provider/server/src/p2p/register.rs
  storage-provider/server/src/p2p/swarm.rs
  storage-provider/server/src/retrieval/mod.rs
  storage-retrieval/cli/Cargo.toml
  storage-retrieval/lib/README.md
  storage-retrieval/lib/examples/chaos_server.rs
  storage-retrieval/lib/examples/simple_server.rs
  storage-retrieval/lib/src/server.rs
Labels: ready for review

#786 feat: add replicated file examples
  examples/rpc_replicated_file.sh
  examples/start_sps.sh
Labels: ready for review
